name: Build and Deploy doc.nuxeo.com

on:
  push:
    branches:
      - master
      - development
  schedule:
    - cron: '0 0 * * *' # Every night at midnight
  workflow_dispatch:  # Manual triggering

jobs:
  documentation_ci:
    name: Build & Publish documentation to ${{ github.ref_name == 'master' && 'production' || 'development' }}
    runs-on: doc
    environment:
      name: ${{ github.ref_name == 'master' && 'production' || 'development' }}
    env:
      SSH_OPTIONS: "-o PubkeyAcceptedKeyTypes=+ssh-rsa"
    steps:

      - name: Set up SSH
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: |
            ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            ${{ secrets.NUXEODEVOPS_SSH_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '14'

      - name: Check Versions and Save to File
        run: |
          echo "git $(git --version)" > runtime-versions.txt
          echo "node version $(node --version)" >> runtime-versions.txt
          echo "npm version $(npm --version)" >> runtime-versions.txt
          echo "IP $(curl -s ipinfo.io/ip)" >> runtime-versions.txt

      - name: Install dependencies
        run: npm ci --registry="https://registry.npmjs.org" || npm install --registry="https://registry.npmjs.org"

      - name: Build
        env:
          ALGOLIA_KEY: ${{ secrets.NX_TOKEN }}
          DEBUG_FILE_LEVEL: debug
        run: npm start

      - name: Generate Nginx Redirects
        run: |
          bin/redirects-yml2nginx > redirects.txt
          echo > redirects_pageid.txt

      - name: Deploy to Server
        run: |
          rsync -e "ssh $SSH_OPTIONS" -Wxvurk --delete site/ "${{ vars.SERVER_USERNAME }}@${{ vars.SERVER_IP }}:/opt/www/doc/"
          rsync -e "ssh $SSH_OPTIONS" redirects.txt "${{ vars.SERVER_USERNAME }}@${{ vars.SERVER_IP }}:/etc/nginx/redirects.txt"
          rsync -e "ssh $SSH_OPTIONS" redirects_pageid.txt ${{ vars.SERVER_USERNAME }}@${{ vars.SERVER_IP }}:/etc/nginx/redirects_pageid.txt

      - name: Nginx Config Test and Restart
        run: |
            ssh $SSH_OPTIONS "${{ vars.SERVER_USERNAME }}@${{ vars.SERVER_IP }}" \
                   "service nginx configtest && service nginx restart"

      - name: Archive Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-artifacts
          path: |
            redirects_pageid.*
            redirects.*
            *.txt
            npm-debug.log
